---
# Rôle : fail2ban — variables par défaut
fail2ban_bantime: 3600
fail2ban_findtime: 600
fail2ban_maxretry: 5
fail2ban_ignoreip: "127.0.0.1/8 192.168.10.0/24"
fail2ban_backend: systemd

fail2ban_sshd_enabled: true
fail2ban_sshd_port: "22"
fail2ban_sshd_maxretry: 3
